//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NgoPhucThinhMystore.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    public partial class OrderDetail
    {
        public int ID { get; set; }
        public int ProductID { get; set; }
        public int OrderID { get; set; }
        public int Quantity { get; set; }
        public decimal UnitPrice { get; set; }
        public string TotalPrice { get; set; }
        public int OrderTotal { get; set; }
        public int ProductImageName { get; set; }
        public int PaymentMethod { get; set; }
        public int ShippingMethod { get; set; }
        public int ShippingAddress { get; set; }    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}
